name: "terraform-plan"

on:
  workflow_dispatch:
  # push:
  # pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./test

permissions: {}

env:
  SERVICE_ACCOUNT: terraform@wip-project-melanmeg.iam.gserviceaccount.com
  PROJECT_NUMBER: 502820203034
  WORKLOAD_IDENTITY_POOL: github-pool
  WORKLOAD_IDENTITY_POOL_PROVIDER: github-pool-provider
  TERRAFORM_VERSION: 1.9.2
  TFCMT_VERSION: 4.13.0

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_IDENTITY_POOL }}/providers/${{ env.WORKLOAD_IDENTITY_POOL_PROVIDER }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # fmt
      - name: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

      # init
      - name: init
        run: terraform init

      # validate
      - name: validate
        run: terraform validate -no-color

      - uses: shmokmt/actions-setup-tfcmt@v2
        with:
          version: v${{ env.TFCMT_VERSION }}

      # plan
      - name: terraform plan
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt --config ${{ github.workspace }}/tfcmt.yml plan -patch -- terraform plan -no-color -input=false
