name: "terraform-apply"

on:
  workflow_dispatch:
  # issue_comment:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: ./test

permissions: {}

env:
  SERVICE_ACCOUNT: terraform@wip-project-melanmeg.iam.gserviceaccount.com
  PROJECT_NUMBER: 502820203034
  WORKLOAD_IDENTITY_POOL: github-pool
  WORKLOAD_IDENTITY_POOL_PROVIDER: github-pool-provider
  TERRAFORM_VERSION: 1.9.2
  TFCMT_VERSION: 4.13.0

jobs:
  terraform-apply:
    # if: contains(github.event.comment.body, '/apply ci')

    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
      actions: write
      checks: read

    steps:
      - uses: actions/checkout@v4
        # with:
        #   clean: false
        #   ref: refs/pull/${{ github.event.issue.number }}/merge

      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_IDENTITY_POOL }}/providers/${{ env.WORKLOAD_IDENTITY_POOL_PROVIDER }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # fmt
      - name: fmt
        run: terraform fmt -recursive -check
        continue-on-error: true

      # init
      - name: init
        run: terraform init

      # validate
      - name: validate
        run: terraform validate -no-color

      - uses: shmokmt/actions-setup-tfcmt@v2
        with:
          version: v${{ env.TFCMT_VERSION }}

      # apply
      - name: terraform apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFCMT_REPO_OWNER: ${{ github.event.organization.name }}
          TFCMT_REPO_NAME: ${{ github.event.repository.name }}
          TFCMT_PR_NUMBER: ${{ github.event.issue.number }}
        run: tfcmt --config ${{ github.workspace }}/tfcmt.yml apply -- terraform apply -no-color -input=false -auto-approve
